{{- if .Values.prometheus.additionalServiceMonitors }}
apiVersion: v1
kind: List
items:
{{- range .Values.prometheus.additionalServiceMonitors }}
  - apiVersion: "monitoring.coreos.com/v1"
    kind: ServiceMonitor
    metadata:
      name: {{ .name }}
      labels:
        app: {{ template "prometheus.name" $ }}-prometheus
{{ include "prometheus.labels" $ | indent 8 }}
        {{- if .additionalLabels }}
{{ toYaml .additionalLabels | indent 8 }}
        {{- end }}
    spec:
      endpoints:
{{ toYaml .endpoints | indent 8 }}
    {{- if .jobLabel }}
      jobLabel: {{ .jobLabel }}
    {{- end }}
    {{- if .namespaceSelector }}
      namespaceSelector:
{{ toYaml .namespaceSelector | indent 8 }}
    {{- end }}
      selector:
{{ toYaml .selector | indent 8 }}
{{- end }}
{{- end }}
