apiVersion: v1
kind: Service
metadata:
  name: collectd-prometheus-metrics-endpoint
  labels:
    app: collectd
    collector: collectd
spec:
  ports:
  - name: collectd-prometheus
    port: {{ .Values.collectd_prometheus.service.port }}
    protocol: TCP
    targetPort: {{ .Values.collectd_prometheus.service.targetPort }}
  selector:
{{ include "rangeskipempty" .Values.collectd_prometheus.service.selector | indent 4 }}
  type: ClusterIP