dependencies:

  - name: prometheus-node-exporter
    version: 1.1.*
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: nodeExporter.enabled

  - name: grafana
    version: 1.24.*
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: grafana.enabled
