apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: {{ .Values.topic.name }}
  labels:
    strimzi.io/cluster: {{ .Values.topic.cluster }}
  annotations:
    "helm.sh/hook": "post-install"  
spec:
  partitions: {{ .Values.topic.partitions }}
  replicas: {{ .Values.topic.replicas }}
