kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: collectd-operator
subjects:
- kind: ServiceAccount
  name: collectd-operator
  namespace: cop
roleRef:
  kind: ClusterRole
  name: collectd-operator
  apiGroup: rbac.authorization.k8s.io
