apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ if .Values.prometheus.configMapName }}{{ .Values.prometheus.configMapName }}{{ else }}{{ template "promql_query_app.fullname" . }}{{ end }}
data:
  prometheus_endpoint: {{ .Values.prometheus.serverURL }}