apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: prometheusremoteendpoints.onap.org
spec:
  group: onap.org
  names:
    kind: PrometheusRemoteEndpoint
    listKind: PrometheusRemoteEndpointList
    plural: prometheusremoteendpoints
    singular: prometheusremoteendpoint
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: PrometheusRemoteEndpoint is the Schema for the prometheusremoteendpoints
        API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: PrometheusRemoteEndpointSpec defines the desired state of PrometheusRemoteEndpoint
          properties:
            adapterURL:
              type: string
            filterSelector:
              additionalProperties:
                type: string
              type: object
            kafkaConfig:
              type: string
            queueConfig:
              description: QueueConfig - defines the prometheus remote write queue
                configurations
              properties:
                batchSendDeadline:
                  type: string
                capacity:
                  type: string
                maxBackoff:
                  type: string
                maxRetries:
                  type: string
                maxSamplesPerSend:
                  type: string
                maxShards:
                  type: string
                minBackoff:
                  type: string
                minShards:
                  type: string
              type: object
            remoteTimeout:
              type: string
            type:
              type: string
          required:
          - adapterURL
          - type
          type: object
        status:
          description: PrometheusRemoteEndpointStatus defines the observed state of
            PrometheusRemoteEndpoint
          properties:
            kafkaWriterID:
              type: string
            prometheusInstance:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "operator-sdk generate k8s" to regenerate
                code after modifying this file Add custom validation using kubebuilder
                tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html
                Status can be Error, Enabled'
              type: string
            remoteURL:
              type: string
            status:
              type: string
          required:
          - status
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
