apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: grafanadatasources.onap.org
spec:
  group: onap.org
  names:
    kind: GrafanaDataSource
    listKind: GrafanaDataSourceList
    plural: grafanadatasources
    singular: grafanadatasource
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: GrafanaDataSource is the Schema for the grafanadatasources API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: GrafanaDataSourceSpec defines the desired state of GrafanaDataSource
          properties:
            datasources:
              items:
                description: Datasource defines the fields in a GrafanaDataSource
                properties:
                  access:
                    type: string
                  basicAuth:
                    type: boolean
                  basicAuthPassword:
                    type: string
                  basicAuthUser:
                    type: string
                  database:
                    type: string
                  isDefault:
                    type: boolean
                  jsonData:
                    additionalProperties:
                      type: string
                    type: object
                  name:
                    type: string
                  password:
                    type: string
                  readOnly:
                    type: boolean
                  type:
                    type: string
                  url:
                    type: string
                  user:
                    type: string
                  withCredentials:
                    type: boolean
                required:
                - access
                - name
                - type
                - url
                type: object
              type: array
            grafana:
              additionalProperties:
                type: string
              type: object
          required:
          - datasources
          - grafana
          type: object
        status:
          description: GrafanaDataSourceStatus defines the observed state of GrafanaDataSource
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
